// Application steps vary structure, constraints and operations, not just variable names.
export type Application={title:string;prompt:string;code:string;answers:string[][];hint:string};
const step=(title:string,prompt:string,code:string,answers:(string|string[])[],hint:string):Application=>({title,prompt,code,answers:answers.map(a=>typeof a==='string'?[a]:a),hint});
export const applications={
 easy:[
 step('Catálogo com preço formatado','Na aplicação, anote o retorno textual da formatação de preço.','function exibirPreco(valor: number): ___ {\n return `R$ ${valor.toFixed(2)}`;\n}\nconsole.log(exibirPreco(149.9));',['string'],'toFixed devolve texto; a interpolação também produz string.'),
 step('Perfil e preferências','Na aplicação, tipifique uma lista mutável de preferências textuais.','const preferencias: ___ = ["email", "tema escuro"];\npreferencias.push("notificações");',[['string[]','Array<string>']],'A coleção aceita vários textos e pode receber novos elementos.'),
 step('Pedido em duas posições','Na aplicação, complete a tupla com o tipo do código e da quantidade, nessa ordem.','const linhaPedido: [___, ___] = ["SKU-42", 3];\nconst [sku, quantidade] = linhaPedido;',['string','number'],'Uma tupla preserva a ordem e o tipo de cada posição.'),
 step('Leituras de um sensor','Na aplicação, tipifique os elementos do histórico numérico.','const leituras: ___[] = [21.5, 22, 23.5];\nconst media = leituras.reduce((a, b) => a + b, 0) / leituras.length;',['number'],'As medidas decimais continuam sendo number.'),
 step('Curso e matrícula','Na aplicação, complete o tipo do parâmetro que decide o acesso ao curso.','function podeAssistir(matriculado: ___): string {\n return matriculado ? "Acesso liberado" : "Faça a matrícula";\n}',['boolean'],'O parâmetro é um sinalizador verdadeiro ou falso.'),
 step('Reserva com observação','Na aplicação, torne observacao opcional, permitindo a reserva mínima.','const reservaMinima: { noites: number; observacao___: string } = { noites: 4 };',['?'],'? após o nome da propriedade permite omiti-la.'),
 step('Tarefa sem retorno','Na aplicação, anote o retorno de uma função que apenas imprime um aviso.','function avisarConclusao(descricao: string): ___ {\n console.log("Concluída: " + descricao);\n}',['void'],'Uma função que só produz um efeito e termina normalmente usa void.'),
 step('Arquivo com tamanho protegido','Na aplicação, impeça reatribuir bytes pelo tipo do objeto.','const metadados: { ___ bytes: number } = { bytes: 4096 };\nconsole.log(metadados.bytes);',['readonly'],'readonly vem antes do nome da propriedade.'),
 step('Agenda e lista de presença','Na aplicação, tipifique a função que recebe o nome de um participante.','const confirmarPresenca = (nomeParticipante: ___): string =>\n "Confirmado: " + nomeParticipante;',['string'],'O nome é textual e a função produz uma mensagem.'),
 step('Conta e limite ausente','Na aplicação, inclua null para representar uma conta sem limite definido.','let limiteCredito: number | ___ = null;\nlimiteCredito = 500;',['null'],'A união precisa representar explicitamente a ausência inicial.'),
 ],
 medium:[
 step('Catálogo com preço promocional','Na aplicação, use Pick para extrair apenas os campos necessários à promoção.','type OfertaBase = { sku: string; preco: number; estoque: number };\ntype Oferta = ___<OfertaBase, "sku" | "preco">;\nconst promocao: Oferta = { sku: "TEC-1", preco: 119 };',['Pick'],'Pick seleciona propriedades e mantém os seus tipos.'),
 step('Perfil carregado com segurança','Na aplicação, refine o dado externo antes de normalizar o email.','function normalizarEmail(entrada: unknown): string {\n if (typeof entrada === ___) return entrada.trim().toLowerCase();\n throw new Error("Email inválido");\n}',['"string"'],'Antes de chamar métodos de texto, refine unknown para string.'),
 step('Pedido com status exclusivo','Na aplicação, complete o discriminante que permite acessar o código de rastreamento.','type Envio = { status: "pendente" } | { status: "enviado"; rastreio: string };\nfunction rastrear(e: Envio): string {\n return e.status === ___ ? e.rastreio : "Aguardando postagem";\n}',['"enviado"'],'Somente o ramo enviado contém rastreio.'),
 step('Sensor com callback de alerta','Na aplicação, tipifique o valor de entrada e a decisão do callback.','function detectarAlerta(valor: number, regra: (v: ___) => ___) {\n return regra(valor);\n}\ndetectarAlerta(38, v => v > 35);',['number','boolean'],'A regra recebe uma medida e responde se ela exige alerta.'),
 step('Curso e conteúdo imutável','Na aplicação, use ReadonlyArray para impedir alterações na lista recebida.','function primeiraAula(aulas: ___<string>): string | undefined {\n return aulas[0];\n}',['ReadonlyArray'],'A função consulta a lista; não precisa modificá-la.'),
 step('Reserva com atualização parcial','Na aplicação, use Partial para aceitar uma atualização só das noites.','type DadosReserva = { hospede: string; noites: number; observacao: string };\nconst alterarReserva: ___<DadosReserva> = { noites: 5 };',['Partial'],'Uma atualização pode informar somente o campo alterado.'),
 step('Tarefa e permissões','Na aplicação, exija uma decisão booleana para cada ação.','type AcaoTarefa = "ler" | "editar" | "excluir";\nconst permissoes: ___<AcaoTarefa, boolean> = { ler: true, editar: true, excluir: false };',['Record'],'Record com uma união finita exige todas as chaves dessa união.'),
 step('Arquivo e resultado opcional','Na aplicação, anote a Promise que resolve um tamanho ou undefined.','async function consultarTamanho(existe: boolean): Promise<number | ___> {\n return existe ? 4096 : undefined;\n}',['undefined'],'A possibilidade de ausência fica dentro da Promise.'),
 step('Evento com composição','Na aplicação, combine a localização e a capacidade sem perder nenhum campo.','type LocalEvento = { cidade: string };\ntype CapacidadeEvento = { vagas: number };\nconst planejamento: LocalEvento ___ CapacidadeEvento = { cidade: "Recife", vagas: 40 };',['&'],'Uma interseção exige os dois conjuntos de propriedades.'),
 step('Conta com chave segura','Na aplicação, obtenha a união das chaves do saldo detalhado.','type SaldoDetalhado = { disponivel: number; bloqueado: number };\ntype ChaveSaldo = ___ SaldoDetalhado;\nconst campoSaldo: ChaveSaldo = "disponivel";',['keyof'],'keyof produz a união de nomes válidos do objeto.'),
 ],
 hard:[
 step('Catálogo e payload de API','Na aplicação, remova estoque antes de tornar os demais campos opcionais.','type ProdutoAPI = { sku: string; preco: number; estoque: number };\ntype PatchPublico = ___<___<ProdutoAPI, "estoque">>;\nconst patchPublico: PatchPublico = { preco: 99 };',['Partial','Omit'],'Aplique Omit ao modelo original; depois envolva o resultado em Partial.'),
 step('Perfil e campos serializáveis','Na aplicação, extraia apenas as chaves de propriedades textuais.','type PerfilBruto = { nome: string; email: string; ultimoAcesso: Date };\ntype CamposTexto<T> = { [K in keyof T]: T[K] extends ___ ? K : ___ }[keyof T];\nconst campoTextual: CamposTexto<PerfilBruto> = "email";',['string','never'],'O mapped type conserva a chave textual e elimina os outros casos com never.'),
 step('Pedido e transição exaustiva','Na aplicação, garanta exaustividade ao tratar as ações de pagamento.','type AcaoPagamento = { tipo: "pagar"; centavos: number } | { tipo: "cancelar" };\nfunction totalAcao(a: AcaoPagamento): number {\n switch(a.tipo) {\n  case "pagar": return a.centavos;\n  case "cancelar": return 0;\n  default: { const restante: ___ = a; return restante; }\n }\n}',['never'],'O compilador deve provar que não sobra nenhum caso no default.'),
 step('Sensor e leitura validada','Na aplicação, complete a asserção para uma medida numérica finita.','function garantirMedida(v: unknown): ___ v ___ number {\n if (typeof v !== "number" || !Number.isFinite(v)) throw new Error("Medida inválida");\n}\nfunction dobroMedida(v: unknown) { garantirMedida(v); return v * 2; }',['asserts','is'],'A asserção refina o argumento depois de uma validação real.'),
 step('Curso e eventos de alteração','Na aplicação, preserve chaves textuais no template literal e associe cada evento ao tipo original.','type CursoEditavel = { titulo: string; aulas: number };\ntype EventosCurso<T> = {\n [K in keyof T as `${K & ___}Changed`]: (novoValor: T[___]) => void\n};\ntype EventosDisponiveis = EventosCurso<CursoEditavel>;',['string','K'],'A interseção com string permite usar a chave no template; T[K] mantém seu tipo.'),
 step('Reserva e tupla assíncrona','Na aplicação, preserve a ordem dos valores resolvidos em paralelo.','async function cotarReserva(): Promise<[___, ___]> {\n return Promise.all([Promise.resolve(320), Promise.resolve("BRL")]);\n}',['number','string'],'Promise.all com uma tupla mantém o tipo de cada posição.'),
 step('Tarefa e atualização por chave','Na aplicação, relacione a nova propriedade à chave genérica.','function editarTarefa<T, K extends keyof T>(alvo: T, chave: K, novo: ___): T {\n return { ...alvo, [chave]: novo };\n}\neditarTarefa({ titulo: "Revisar", concluida: false }, "concluida", true);',['T[K]'],'O valor deve ter o tipo da propriedade escolhida, não uma união de todos os tipos.'),
 step('Arquivo e inferência de retorno','Na aplicação, extraia o valor resolvido da função de leitura.','async function lerConteudo() { return { bytes: new Uint8Array([1, 2]), mime: "application/octet-stream" }; }\ntype ConteudoLido = ___<___<typeof lerConteudo>>;',['Awaited','ReturnType'],'ReturnType obtém a Promise e Awaited extrai seu conteúdo.'),
 step('Evento e assinaturas variádicas','Na aplicação, preserve a tupla genérica dos argumentos do callback.','function envolverEvento<A extends unknown[], R>(fn: (...args: ___) => R) {\n return (...args: A): ___ => fn(...args);\n}\nconst nomeEvento = envolverEvento((titulo: string, ano: number) => `${titulo} ${ano}`);',['A','R'],'A representa todos os parâmetros como uma tupla, e R preserva o retorno.'),
 step('Conta e filtro de tipos','Na aplicação, retenha apenas o resultado de sucesso usando Extract.','type OperacaoConta = { ok: true; saldo: number } | { ok: false; motivo: string };\ntype CreditoConfirmado = ___<OperacaoConta, { ok: ___ }>;\nconst credito: CreditoConfirmado = { ok: true, saldo: 500 };',['Extract','true'],'Extract escolhe os membros compatíveis com o discriminante informado.'),
 ],
};
